### your site title here

title: 游戏暂停
baseurl:  # name of the repository
email: li.jw@me.com
name: 游戏暂停
description: 李家伟的博客。
url: http://lijiawei.cc


highlighter: rouge
markdown: Kramdown
### exclude the instructions / write-up in the README.md

permalink: posts/:title/

# Tracker
analytics: UA-92264874-1

# Comments
disqus-shortname: you-xi-zan-ting

collections:
  essays:
    output: true
    permalink: essays/:title/

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
 style: compressed

exclude:
- README.md


plugins: [jekyll-seo-tag]
